config/routes.rb
Rails.application.routes.draw do
  root'home#index'

  get 'home/index'
  get 'home/checkr'
  get 'home/flynn'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def checkr
  end

  def flynn
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/checkr.html.erb
<% provide :stylesheets, 'checkr' %>
<div class="bg">
<header>
	<div class="navbar">
	<a href="#" class="logo"> </a>
  		<div class="dropdown">
	    	<button class="dropbtn">PRODUCT 
	      		<i class="fa fa-caret-down"></i>
	    	</button>
		    <div class="dropdown-content">
				<a href="#">Overview</a>
				<a href="#">screening</a>
				<a href="#">Compliance</a>
				<a href="#">Security</a>
		    </div>
	  	</div>
	  	<div class="dropdown">
	    	<button class="dropbtn">STAFFING 
	      		<i class="fa fa-caret-down"></i>
	    	</button>
		    <div class="dropdown-content">
				<a href="#">Overview</a>
		    </div>
	  	</div>
	  	<div class="dropdown">
	    	<button class="dropbtn">INDUSTRIES
	      		<i class="fa fa-caret-down"></i>
	    	</button>
		    <div class="dropdown-content">
				<a href="">Overview</a>
				<a href="">Staffing</a>
				<a href="">Contact Centers</a>
				<a href="">Financial Services</a>
				<a href="">Retail &amp Hospitality</a>
				<a href="">Healthcare</a>
				<a href="">Non-Profit</a>
				<a href="">On-Demand Economy</a>
				<a href="">Manufacturing</a>
				<a href="">Software &amp Technology</a>
				<a href="">Small Business</a>
				<a href="">P2P Marketplaces</a>
		    </div>
	  	</div>
	  	<div class="dropdown">
	    	<button class="dropbtn">RESSOURCES 
	      		<i class="fa fa-caret-down"></i>
	    	</button>
		    <div class="dropdown-content">
				<a href="#">Overview</a>
				<a href="#">screening</a>
				<a href="#">Compliance</a>
				<a href="#">Security</a>
		    </div>
	  	</div>
	  	<div class="dropdown">
	    	<button class="dropbtn">COMPLIANCE 
	    	</button>
	    </div>
	</div>
	<!-- <div class="container">		
		<nav class="primary-nav">
			<ul>
				<li>
					<a href="" class="logo"></a>
				</li>
				<li class="dropdown-menu-product">
					<a href="" class="dropdown-toggle"></a>
					<ul class="dropdown-menu">
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
					</ul>
				</li>
				<li class="dropdown-menu-staffing">
					<a href="" class="dropdown-toggle"></a>
					<ul class="dropdown-menu">
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
					</ul>
				</li>
				<li class="dropdown-menu-industries">
					<a href="" class="dropdown-toggle"></a>
					<ul class="dropdown-menu">
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
					</ul>
				</li>
				<li class="dropdown-menu-ressources">
					<a href="" class="dropdown-toggle"></a>
					<ul class="dropdown-menu">
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
						<li class="menu"></li>
					</ul>
				</li>
				<li class="dropdown-menu-compliance">
					<a href=""></a>
				</li>
			</ul>
		</nav>
		<nav class="top-nav">
			<ul>
				<li>
					<a href="">I Am an Applicant</a>
				</li>
				<li>
					<a href="">API &amp Doc</a>
				</li>
				<li>
					<a href="">About Us</a>
				</li>
				<li>
					<a href="">Careers</a>
				</li>
			</ul>
		</nav>
		<nav class="right-nav">
			<ul>
				<li>
					<a href="">Log in</a>
				</li>
				<li>
					<a href="">Get started</a>
				</li>
			</ul>
		</nav>
	</div> -->
</header>

<div class="wrapper">
  	<div class="box text">
      	<h1>HIRE GREAT PEOPLE. FASTER.</h1>
	    <p>Checkr provides modern and compliant background checks for global enterprises and startups.</p>
	    <button type="button" class="btn"> EXPLORE NOW <i class="fas fa-arrow-right"></i></button>
	</div>
  	<div class="box video">
    <%= video_tag "Checkr_Hero.mp4", autoplay: true %>
    </div>
</div>

</div><!-- Fin du BG img -->
<!-- ###################### -->
<div class="home-hero">
	<h3>More Than 10,000 Businesses Trust Checkr for Their Background Screenings</h3>
	<div class="panel">
		<img src="https://checkr.com/wp-content/uploads/2016/02/Uber_white_2@2x.jpeg" alt="logo">
		<img src="https://checkr.com/wp-content/uploads/2015/10/instacart-logo@2x.png" alt="logo">
		<img src="https://checkr.com/wp-content/uploads/2018/02/Grubhub-logo.png" alt="logo">
		<img src="https://checkr.com/wp-content/uploads/2015/10/postmates_logo_s-1.png" alt="logo">
		<img src="https://checkr.com/wp-content/uploads/2015/10/zenefits.gif" alt="logo">
		<img src="https://checkr.com/wp-content/uploads/2018/02/lyft_high_res.png" alt="logo">
	</div>
</div>
<!-- ###################### -->

<div class=background-check>
	<h3>The Next Generation of Background Checks</h3>
	<div class="wrapper2">
		<div class="box2 a">
		  	<i class="fas fa-mobile-alt fa-3x"></i><br>
		  	<h5>Mobile-Friendly</h5>
			<p>Create a positive applicant experience with simple, mobile-friendly onboarding.</p>
		</div>
	  	<div class="box2 b">
	  		<i class="fas fa-desktop fa-3x"></i><br>
		  	<h5>Easy to Understand</h5>
			<p>Color-coded reports and an intuitive interface makes it possible to review information faster. See a sample employee background report.</p>
		</div>
  		<div class="box2 c">
  			<i class="fas fa-cogs fa-3x"></i><br>
		  	<h5>Convenient Automation</h5>
			<p>Reports and violations are categorized to help you remain compliant with individual assessment requirements.</p>
		</div>
  		<div class="box2 d">
  			<i class="far fa-comments fa-3x"></i><br>
		  	<h5>Simplified and Compliant Communication</h5>
			<p>Automated compliance tools allow you to send adverse action communications in seconds, directly from your dashboard.</p>
		</div>
	    <div class="box2 e">
	    	<i class="far fa-chart-bar fa-3x"></i><br>
		  	<h5>Fast and Accurate</h5>
			<p>Understand the profile of your applicants and find the best pool of candidates using integrated analytics and reports.</p>
		</div>  
	</div> <!-- Fin du Wrapper2 -->
</div><!-- Fin des industry-need -->	

<div class="industry-need"></div>
<div class="compliance-security"></div>
<div class="schedule-demo"></div>
<div class="footer"></div>

app/views/home/flynn.html.erb
<h1>Home#flynn</h1>
<p>Find me in app/views/home/flynn.html.erb</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>


<p><%= link_to("Voir la landing page de Checkr", home_checkr_path) %></p>
<p><%= link_to("Voir la landing page de Flynn", home_flynn_path) %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LandingPages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag  yield(:stylesheets) , media: 'all', 'data-turbolinks-track': 'reload' %>
    
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- \o/ Font-Awesome \o/ -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
  </head>


  <body>
    <%= yield %>
  </body>
</html>